stages:
  - uhd
  - gnuradio
  - fpga

.conditionals: &conditionals
  refs:
    - master
    - branches
    - web

.uhd-build: &uhd-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=0
  - make -j10

.gnuradio-build: &gnuradio-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=1
  - make -j10

.fpga-script: &fpga-script
  - rm -rf ../uhd-fpga && git clone -b UHD-3.13 https://github.com/EttusResearch/fpga.git ../uhd-fpga
  - export UHD_FPGA_DIR=`pwd`/../uhd-fpga
  - source /opt/Xilinx/Vivado/2017.4/settings64.sh
  - cd fpga-rfnoc/testbenches
  - for d in ./*/ ; do (cd "$d" && pwd && make clean && ./runtestbench.sh); done

build-uhd-3.15:
  stage: uhd
  image: theseuscores/uhd:UHD-3.15.LTS-rfnoc-all
  script: *uhd-build
  only: *conditionals

build-gnuradio-maint-3.8-uhd-3.15:
  stage: gnuradio
  image: theseuscores/gnuradio:maint-3.8-UHD-3.15-rfnoc
  script: *gnuradio-build
  only: *conditionals

fpga-test-merge:
  stage: fpga
  script: *fpga-script
  only:
    refs:
      - merge_requests
    changes:
      - fpga-rfnoc/**/*
      - fpga-src/**/*
  tags:
    - vivado

fpga-test-master:
  stage: fpga
  script: *fpga-script
  only:
    refs:
      - master
      - web
  tags:
    - vivado
